### PR TITLE
Fix no clipping when source density is high

### LINKED ISSUE #7: rms too high
I constructed a 4k*4k image with 409² 100 Jy sources with a Gaussian profile on a regular grid, inspired by the authors of [this paper](https://www.cse.ust.hk/catalac/papers/source_extraction_escience2013.pdf). They use the same size image, with 167000 sources. 
I inserted those sources in the image plane on top of pure Gaussian - so uncorrelated - noise with a std of 1 Jy.

I ran 
`pyse --detection=50 --analysis=50 --grid=4096 --rmsmap --islands SOURCESINSERTED_100Jy.FITS` to get a single noise level - should be close to 1 Jy - and, hopefully 167281 detections.

Unfortunately, the rms value from the rms.fits is 19.5608 Jy. Way too high and way higher than the ground truth of 1 Jy.

Same output with pyse.py from the tkp repo.

### PR DESCRIPTION
**Pull request by HannoSpreeuw**
Fixes #7 

However, it involves quite an overhaul of stats.sigma_clip.
In summary, what I ran into with an artificial 4K * 4K image with 167000 sources of ~ 100 Jy on top of Gaussian noise with an std of 1 Jy is that no clipping was done at all, because the initial estimate of the std - so before any clipping- of the background noise was so high: over 19 Jy.
The dynamical clipping limit related to equation 2.22 of my thesis set kappa equal to about five, I believe, and all pixels were below that limit of kappa * 19 Jy.

Now the dynamical clipping limit ensures that any parameters derived from the clipped distribution are not biased by clipping. 
No bias is good, so when dropping the dynamical clipping limit something else is needed to correct for the clipping bias.
I could do that by solving for sigma in the transcendental equation 2.25 from my thesis, using the new module find_true_std.
(Previously var_helper was used, which combines 2.22 and 2.25, making it non-transcendental and easy to derive the correction for the clipping bias).

I set kappa=2 fixed, so there will virtually always be clipping at the limit of kappa * std.
(Note that there is a lower limit to kappa, find_true_std will not have any roots for kappa < sqrt(3), This means that equation 2.25 of my thesis does not have any solutions for D/sigma < sqrt(3), this is not so hard to prove.)

I also removed the beam properties (self.beam in image.py) from the input to stats.sigma_clip. The size of the synthesized beam was needed to make an estimate of the number of independent pixels in the subimage, but with 2.22 (dynamical clipping limit) removed from the calculations, this is no longer needed. It also appeared in corrections for biases of the variances from limited sample sizes (number of independent pixels in the subimage), but these corrections turn out to be so small for any subimage of reasonable size that they can be neglected. Same for the "c4" correction to the standard deviation.

### CODE REVIEW

File: gitlistobjectbysize.sh [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+	git ls-tree -r --long "$commitSHA1" >>"$tempFile"
+done
+
+# sort files by SHA1, de-dupe list and finally re-sort by filesize
+sort --key 3 "$tempFile" | \
+	uniq | \
+	sort --key 4 --numeric-sort --reverse
+
+# remove temp file
+rm "$tempFile"
```
Comment (gijzelaerr) [inline gitlistobjectbysize.sh:16]: i think you can do `git rev-list --all | xargs git ls-tree -r --long | sort --key 3 | uniq | sort --key 4 --numeric-sort --reverse` (without temp file)

File: sourcefinder/stats.py [hunk 2]
```diff
@@ -7,58 +7,26 @@
...
-    rms noise only.
-    """
-    term1 = numpy.sqrt(2. * numpy.pi) * erf(N / numpy.sqrt(2.))
-    term2 = 2. * N * numpy.exp(-N ** 2 / 2.)
-    return term1 / (term1 - term2)
-
+def find_true_std(sigma, clip_limit, clipped_std):
+    help1 = clip_limit/(sigma*numpy.sqrt(2))
+    help2 = numpy.sqrt(2*numpy.pi)*erf(help1)
+    return sigma**2*(help2-2*numpy.sqrt(2)*help1*numpy.exp(-help1**2))-clipped_std**2*help2
```
Comment (gijzelaerr) [inline sourcefinder/stats.py:20]: this is not pep8 compatible formatting

**Review by gijzelaerr — APPROVED** [review]

File: gitlistobjectbysize.sh (hunk 1 above)
Comment (HannoSpreeuw) [reply gitlistobjectbysize.sh:16]: Thanks. 
I got that script from [here](https://gist.github.com/magnetikonline/dd5837d597722c9c2d5dfa16d8efe5b9).
I should not have committed it.
I was investigating [this Travis issue](https://travis-ci.org/github/transientskp/pyse/builds/727059272):
```
This repository is over its data quota.
```

So I investigated that using gitlistobjectbysize.sh:

```
100644 blob c946c7699e484795841a65a5a76e8267acbce451 1048576    test/data/SWIFT_554620-130504.image/table.f0_TSM0
100644 blob 442a8965a21b4b3759a13f975a17c30e9b66b0e3   98816    test/data/SWIFT_554620-130504.image/logtable/table.f0
```

Comment (HannoSpreeuw) [reply gitlistobjectbysize.sh:16]: Can those two files be removed?
Requires rewriting history:
```
git filter-branch \
	--tree-filter "rm -f something/really/large.iso" \
	-- --all
```

**Comment by gijzelaerr** [comment]
They could, but probably wise to replace them with something smaller to
make sure the test suite still runs. Not sure what the state of the test
suite is btw, it has been a while.

Op di 15 sep. 2020 10:49 schreef Hanno Spreeuw <notifications@github.com>:

File: sourcefinder/stats.py (hunk 2 above)
Comment (HannoSpreeuw) [reply sourcefinder/stats.py:19]: My IDE (PyCharm) indeed indicated that two blank lines are required after each function, according to PEP8.
Is that what you mean?

**Comment by HannoSpreeuw** [comment]
> They could, but probably wise to replace them with something smaller to make sure the test suite still runs. Not sure what the state of the test suite is btw, it has been a while.

I really don't understand. The Travis message is about a 1 MB file, while GH repos can contain [at least 100 MB](https://stackoverflow.com/questions/38768454/repository-size-limits-for-github-com).

Perhaps Travis imposes additional constraints.

**Comment by HannoSpreeuw** [comment]
Disk quota problem has been fixed by adding
```
git:
  depth: false
```
to `.travis.yml`.
Still a travis build failure, from four failing nosetests, from this command that Travis runs:
```
docker run transientskp/pyse nosetests --with-coverage --cover-package=sourcefinder
```

I am trying to reproduce these four fails by running nosetests from the command line.
However, that gives me a number of different errors:
```
 raise IOError("unsupported format: %s" % filename)
OSError: unsupported format:
```
So it has problems opening the FITS files in the test directory.
That raises the question: "Have these nosetests perhaps not been run for a long time?".

**Comment by HannoSpreeuw** [comment]
Of course, these are pointer files. Duh. Sorry folks.

**Comment by HannoSpreeuw** [comment]
Presently I am busy fixing broken unit tests. There are quite a few.
These come from the slightly different noise levels caused by the modifications of stats.sigma_clip.

The way some of these unit tests are written is that they put very tight constraints on the noise levels from stats.sigma_clip.
As if the original version of stats.sigma_clip was perfect.

For instance, [this test](https://github.com/transientskp/pyse/blob/a8310c2967bf597d265376e7e5bd8ca598bb34be/test/test_image.py#L395) presently fails because two sources are detected instead of one. The second one near ds9 pixel coordinates (46,381) of GRB120422A-120429.fits. It will appear just above the 5 sigma detection limit if the noise level is computed slightly lower, as it presently does compared to the original version.

Same for [this test](https://github.com/transientskp/pyse/blob/a8310c2967bf597d265376e7e5bd8ca598bb34be/test/test_image.py#L274l). Also, there is a `self.assertAlmostEqual(r[i], known_result[i], places=5)` which imposes a very tight constraint on the output, which cannot be matched with the required level of accuracy (five decimal places) if noise levels differ by 10% or so, which is a rather modest difference between the output of two clipping algorithms in the presence of many sources or sidelobes from calibration errors.
